### ISSUE TITLE
Beacon scanning packet types too broad

### ISSUE THREAD

**Issue by astephon88** [linjmeyer/tilt-pitch#14]
As currently configured, the beacon scanner returns any beacon type it detects. Since _beacon_callback is assuming everything it receives is an iBeacon packet, it may try to access fields that don't exist. For example, I am frequently picking up ExposureNotificationFrame packets that do not contain a uuid, which causes tilt-pitch to crash when trying to access that field.

**Comment by linjmeyer** [comment]
Fixed in v0.7.1
