### ISSUE TITLE
Request - Support for Brewfather

### ISSUE THREAD

**Issue by thomassandberg** [linjmeyer/tilt-pitch#2]
Would have been awesome to have built in support for Brewfather. https://docs.brewfather.app/

Using TiltPi --> Brewfather today but tilt-pitch seems like a better alternative.

**Comment by linjmeyer** [comment]
Hi!  Added support for Brewfather's custom stream API in release `v0.4.0`.  I did some testing and it seems to be working, feel free to give it a shot.  Let me know if you have any issues, I don't use Brewfather so it's possible I missed something.
