### ISSUE TITLE
web UI or Command line ?

### ISSUE THREAD

**Issue by tromaxland** [linjmeyer/tilt-pitch#22]
Hi, thanks for the grainfather request. I had a hard time upgrading my old laptop to ubuntu 20.xx to install tilt-pitch.

I "think" it is running.  i have this in the terminal window:

Starting...
...started: Prometheus (http://127.0.0.1:8000/metrics)
...started: File (pitch_log.json) 
...started: Grainfather Custom URL 
...started: Tilt scanner
Ready!  Listening for beacons

Question: is there a web interface ?

pitch_log.json is 0 bytes so i cannot tell if anything is wrong.

Merci,

Mario

**Comment by linjmeyer** [comment]
There is no web UI, just the command line.  It will log beacons it receives to the console plus some nicer json formatted values to the pitch_log.json.   Based on what you shared everything is running okay, two explanations are that the computer's Bluetooth is just not receiving a signal from Tilt, or that there is a configuration issue on the OS level preventing Bluetooth from working.

You mentioned you are on Ubuntu, did you run the prereqs? https://github.com/linjmeyer/tilt-pitch/blob/master/examples/install/prereqs.sh  I have never tested that script on Ubuntu, but I have on my Raspberry Pi which is Debian based and very similar to Ubuntu.  I would expect it to work the same.

Another thing you can try is running pitch with sudo (root) like `sudo python3 -m pitch`.  That would explain if it's a permissions issue.

Let me know how that goes, I'm not a Linux expert but I can try and help!

**Comment by mvberg** [comment]
Had a similar situation on a [RPI clone](https://libre.computer/products/aml-s905x-cc/).

Had to do: 

```bash
bluetoothctl
scan on
quit
```

Then the bacons started showing up in pitch.

Related issue from `beacontools` [here](https://github.com/citruz/beacontools/issues/65#issuecomment-2015311429)

Thanks for the software @linjmeyer! A beer is on its way.
