### ISSUE TITLE
Yellow tilt reports as Pink

### ISSUE THREAD

**Issue by ShawnBuckley** [linjmeyer/tilt-pitch#27]
I'm having an issue where my yellow tilt is reported as a pink one. The UUID in packets is reported as the same as the pink one which is `a495bb70-c5b1-4b44-b512-1370f02d74de`. It is a new production yellow tilt marked part number BB70 that was purchased last week.

**Comment by linjmeyer** [comment]
Yep sorry, typo.  Fixed in `v0.8.4` which should be available for download a few minutes after this post.
