### ISSUE TITLE
Crash due to casting issue when invalid gravity detected.

### ISSUE THREAD

**Issue by jslay77** [linjmeyer/tilt-pitch#31]
File "/home/jslay/.local/lib/python3.8/site-packages/pitch/pitch.py", line 138, in _beacon_callback
    print("Ignoring broadcast due to invalid gravity: " + tilt_status.gravity)
TypeError: can only concatenate str (not "float") to str

**Comment by linjmeyer** [comment]
Yep, fixed in v0.9.1
